export const types = {
    GET_QUESTIONS_SUCCESS: 'GET_QUESTIONS_SUCCESS',
    GET_QUESTIONS_LOADING: 'GET_QUESTIONS_LOADING',
    GET_QUESTIONS_FAIL: 'GET_QUESTIONS_FAIL',
    UPDATE_QUESTION: 'UPDATE_QUESTION',
    DELETE_QUESTION: 'DELETE_QUESTION'
};
