export const types = {
    GET_QUESTIONS_SUCCESS: 'GET_QUESTIONS_SUCCESS',
    GET_QUESTIONS_LOADING: 'GET_QUESTIONS_LOADING',
    GET_QUESTIONS_FAIL: 'GET_QUESTIONS_FAIL',
    UPDATE_QUESTION: 'UPDATE_QUESTION',
    UPDATE_ANSWER: 'UPDATE_ANSWER',
    DELETE_QUESTION_SUCCESS: 'DELETE_QUESTION_SUCCESS',
    DELETE_QUESTION_FAIL: 'DELETE_QUESTION_FAIL',
    DELETE_QUESTION_REVERT_ALERT: 'DELETE_QUESTION_REVERT_ALERT',
    DELETE_ANSWER_SUCCESS: 'DELETE_ANSWER_SUCCESS',
    DELETE_ANSWER_FAIL: 'DELETE_ANSWER_FAIL',
    DELETE_ANSWER_REVERT_ALERT: 'DELETE_ANSWER_REVERT_ALERT',
    REORDER_QUESTION_UP_SUCCESS: 'REORDER_QUESTION_UP_SUCCESS',
    REORDER_QUESTION_DOWN_SUCCESS: 'REORDER_QUESTION_DOWN_SUCCESS'
};
